import type { NextPage } from "next";
import Head from "next/head";
import HomePage from "./home-page";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Auto-Sign</title>
        <meta name="description" content="Generated by next.js" />
        <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage />
    </div>
  );
};

export default Home;
