import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Auto-Sign</title>
        <meta name="description" content="Generated by next.js" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        
      </div>
    </div>
  );
};

export default Home;
